services: 


  pythonapp:
    build: ./python/
    command: sh -c "python3 ./os.py"
    depends_on:
      - mysql-database

  mysql-database:
    image: mysql:latest 
    ports: 
      - 3302:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  
  postgres-database: 
    image: postgres:latest
    ports:
      - 3303:5432
    environment:
      POSTGRES_PASSWORD: password